#!/bin/bash

SOURCE_DIR="/tmp/shellscript-logs"

if [ ! -d $SOURCE_DIR ]
then
    echo -e "source directory not exist"
fi

FILE_TO_DELETE=$(find $SOURCE_DIR -type f -mtime +14 "*.log")

#IFS internal feild separater
while IFS= read -r line
do 
    echo "Deleting file: $line"
    rm -rf $line
    
done <<< $FILES_TO_DELETE #this output given to input for while loop ,line by line old records will get deleted  <<< denote input