- name: variable from play level
  hosts: localhost
  vars:
    Course: "Devops"
    Trainer: "Bhavani"
    Duration: "10 hours"
  tasks:
  - name: check variables
    vars:
      Course: "devops with AWSS" #task level variables , it is concept of inheritence .
    ansible.builtin.debug:
      msg: "hi i am learning {{Course}}, Trainer is {{Trainer}}, durtaio is {{Duration}}"